vuestorefront-community/spree

README.md, packages/api-client/src/api/logIn/index.ts, packages/api-client/src/index.server.ts, packages/api-client/src/types/index.ts, packages/composables/src/useUser/index.ts, packages/theme/middleware.config.js
This one addresses #41 
I also added a configuration object, that we'll use for enabling/disabling certain features. I believe the next ones that will land in there will be wishlists and potentially reviews.
=> Add associating guest carts

README.md, docs/guide/getting-started.md, packages/api-client/src/api/forgotPassword/index.ts, packages/api-client/src/api/resetPassword/index.ts, packages/api-client/src/index.server.ts, packages/api-client/src/types/index.ts, packages/composables/src/getters/forgotPasswordGetters.ts, packages/composables/src/types/index.ts, packages/composables/src/useForgotPassword/index.ts
=> feat(#36): add forgot password functionality

packages/api-client/src/api/logIn/index.ts
=> fix(#84): remove associating cart if guest cart token is not available

packages/api-client/package.json, packages/composables/package.json, packages/theme/package.json
=> chore: bump package version to 1.1.0

packages/theme/components/Checkout/ShippingRatePicker.vue
=> feat(#91): show message when shipment does not have any shipping methods

packages/api-client/src/api/authentication/getAuthenticationHeaders.ts, packages/api-client/src/api/authentication/getAuthorizationHeaders.ts, packages/api-client/src/api/getPaymentConfirmationData/index.ts, packages/api-client/src/api/getShipments/index.ts, packages/api-client/src/api/handlePaymentConfirmationResponse/index.ts, packages/api-client/src/api/makeOrder/index.ts, packages/api-client/src/api/saveCheckoutBillingAddress/index.ts, packages/api-client/src/api/saveCheckoutShippingAddress/index.ts, packages/api-client/src/api/saveGuestCheckoutEmail/index.ts, packages/api-client/src/api/savePaymentMethod/index.ts, packages/api-client/src/api/saveShippingMethod/index.ts
Some of the checkout api-client methods are using cart token for authentication. However, when user successfully log in, his cart token is removed from cookies so these methods won't work. In that case, we should use his bearer token.
=> fix(api): update authentication tokens in api-client methods

packages/theme/middleware/checkout.js
=> feat(#76): add checkout middleware

packages/theme/components/CartSidebar.vue
Add min="1" argument to the SfQuantitySelector component.
Created a copy of the CartSidebar component and pass an additional argument to the SfQuantitySelector component which disables the "decrement" button if quantity equals to specified min value. 
Documentation:
https://docs.storefrontui.io/?path=/docs/components-atoms-quantityselector--common
#130 
Solves the problem of having the "decrement" button for items quantity enabled if there is only one item in the shopping cart.
=> fix(#130): disable the decrement quantity button if only one item left

packages/theme/pages/Checkout/Shipping.vue
=> feat(#131): add option to save address in shipping page

.github/workflows/conventional-pr-name.yml
=> chore: update workflow config

packages/theme/components/MyAccount/BillingAddressForm.vue, packages/theme/components/MyAccount/ShippingAddressForm.vue, packages/theme/components/UserBillingAddress.vue, packages/theme/components/UserShippingAddress.vue, packages/theme/pages/Checkout/Billing.vue, packages/theme/pages/Checkout/Shipping.vue
=> feat: update address forms in checkout and account pages

packages/theme/pages/MyAccount.vue
Removed  "My newsletter" tab from account page 
Copied the code used by default by vsf and deleted my newsletter page/tab.
#146
It resolves #146 
manually
=> feat: remove My newsletter tab

packages/composables/src/useUser/index.ts
=> fix: update wishlist after login, logout and register

packages/api-client/src/api/deleteAddress/index.ts, packages/api-client/src/index.server.ts, packages/composables/src/useUserBilling/index.ts, packages/composables/src/useUserShipping/index.ts
=> feat(#133): add option to remove saved address

packages/api-client/src/api/changePassword/index.ts, packages/theme/components/MyAccount/PasswordResetForm.vue, packages/theme/pages/MyAccount/MyProfile.vue
Added option for users to change password in user panel.
Added PasswordResetForm and introduced potential rules for password creation. Fixed changePassword Api to match the query which can be found in spree/sdk documentation, copied my profile page from "base" vsf and edited it to pass empty "old password" parameter since spree does not want to check it while changing password.
#150
It fulfils #150
manually
=> feat(#150): add password change page in user panel

packages/theme/components/RelatedProducts.vue
=> fix(#161): update regular price on product cards

packages/composables/src/useCart/index.ts
Changed returned params by applyCoupon to match factory
Changed applyCoupon and removeCoupon to match factory structure so the actual params are updated in "Order Summary"
#167
It is actually possible to apply promotion code without refreshing page
manually
=> fix(#167): add promotion code

packages/api-client/src/api/getCurrentUser/index.ts, packages/api-client/src/api/registerUser/index.ts, packages/api-client/src/api/serializers/user.ts, packages/api-client/src/api/updateCurrentUser/index.ts, packages/api-client/src/index.server.ts, packages/api-client/src/types/index.ts, packages/api-client/src/types/user.ts, packages/composables/src/getters/userGetters.ts, packages/composables/src/types/index.ts, packages/composables/src/useUser/index.ts, packages/theme/components/MyAccount/ProfileUpdateForm.vue
As discussed during stand-ups we wanted to implement My Profile page for the page to look better and less like a mockup.
These changes implement a "My profile" page in user's panel. It 
Closes #148 
It was tested in the local environment with the test Heroku-hosted backend.
=> feat: introduced user's profile page that shows useful information

packages/api-client/src/api/getWishlist/index.ts, packages/api-client/src/types/wishlist.ts, packages/composables/src/getters/wishlistGetters.ts, packages/theme/components/AppHeader.vue, packages/theme/components/BottomNavigation.vue, packages/theme/components/RelatedProducts.vue, packages/theme/pages/Category.vue, packages/theme/pages/Home.vue
=> feat(#176): hide wishlist button if wishlists are disabled

packages/theme/components/CartSidebar.vue, packages/theme/components/WishlistSidebar.vue
The wishlist sidebar was displaying wrong text when it was empty. Also removed the image from it (and from cart), because we don't even have a source file and it takes a lot of space.
FIY.
It was a mistake made in the default Vue Storefront implementation, not ours :)
Closes #175 
It was tested in the local environment connected to the demo backend.
Before vs after
<div>
</div>
=> fix(#175): wishlists text update

packages/theme/pages/MyAccount.vue
My-account page breadcrumbs didn't have any specified links, so they would lead you to the same page. That had to be fixed.
Closes #177 
It was tested in the local environment connected to test Heroku backend.
=> fix(#177): my account breadcrumbs

packages/api-client/src/api/serializers/cart.ts, packages/api-client/src/api/serializers/product.ts, packages/api-client/src/types/cart.ts, packages/api-client/src/types/product.ts, packages/composables/src/getters/productGetters.ts, packages/theme/pages/Product.vue
- Removed hard coded stuff ('The Karissa V-Neck...")
- Placed the description in the right place
- Improved fetching description from the API
- Renamed the "Additional info" Tab to "Properties" and moved properties there
- Changed the "Size guide" button place from above to below the size select component (more intuitive IMO)
- Small style changes to improve the general look and feel of the page
Closes #188 
It makes the app look more real and intuitive
It was tested in the local environment connected to our Heroku backend.
Before
After
=> feat(#188): product pages improvements

packages/theme/components/AppHeader.vue, packages/theme/components/BottomNavigation.vue, packages/theme/components/CartSidebar.vue, packages/theme/middleware.config.js
The top home button (a shopping bug icon) and home button in the bottom navigation were causing the app to crash on the mobile version. It would just freeze. It had to be taken care of.
What's more I fixed a small bug which I introduced in PR #186 where I called the method "getItemId" instead of "getItemVariantId" from cartGetters.
Closes #163
It was tested in the local environment and on the smartphone.
=> fix(#163): fixed mobile bottom navigation buttons and used their isActive property

packages/api-client/src/api/addToCart/index.ts, packages/api-client/src/api/authentication/getCurrentBearerToken.ts, packages/api-client/src/api/getCart/index.ts, packages/api-client/src/api/getCategory/index.ts, packages/api-client/src/api/getOrCreateCart/index.ts, packages/api-client/src/api/getPaymentConfirmationData/index.ts, packages/api-client/src/api/getPaymentMethods/index.ts, packages/api-client/src/api/getProduct/index.ts, packages/api-client/src/api/getProducts/index.ts, packages/api-client/src/api/getShipments/index.ts, packages/api-client/src/api/handlePaymentConfirmationResponse/index.ts, packages/api-client/src/api/makeOrder/index.ts, packages/api-client/src/api/removeFromCart/index.ts, packages/api-client/src/api/saveGuestCheckoutEmail/index.ts, packages/api-client/src/api/saveShippingMethod/index.ts, packages/api-client/src/api/updateItemQuantity/index.ts, packages/composables/src/useReview/index.ts, packages/composables/src/useStore/index.ts, packages/composables/src/useUserBilling/index.ts, packages/composables/src/useUserShipping/index.ts, packages/theme/components/CartSidebar.vue, packages/theme/components/Checkout/PaymentMethod/Check.vue, packages/theme/components/Checkout/PaymentMethod/Stripe.vue, packages/theme/components/Checkout/VsfPaymentProvider.vue, packages/theme/nuxt.config.js, packages/theme/pages/Checkout/Payment.vue, packages/theme/pages/Home.vue, scripts/lib/publishNpm.js, scripts/publishApi.js, scripts/publishComposable.js
=> feat: replace logging calls with Logger

packages/theme/components/AppHeader.vue
With this commit, the wishlist icon badge is displayed.
Resolves #206 
https://user-images.githubusercontent.com/18665370/162470276-2d3fc9fd-fa25-4614-ac3d-dc59d04cc501.mov
=> feat(#206): add wishlist icon badge 

packages/api-client/src/api/getOrder/index.ts, packages/api-client/src/index.server.ts, packages/api-client/src/types/index.ts, packages/composables/src/types/index.ts, packages/composables/src/useUserOrder/index.ts, packages/theme/middleware/order-details.js, packages/theme/nuxt.config.js, packages/theme/pages/MyAccount.vue, packages/theme/pages/MyAccount/MyNewsletter.vue, packages/theme/pages/MyAccount/OrderDetails.vue, packages/theme/pages/MyAccount/OrderHistory.vue
With this commit, each order has its own path in the app router `/my-account/order-details/<order-id>`.
I've transformed reactive order details/order history in the `OrderHistory` file into two separate files that support dynamic routing: `OrderHistory` and `OrderDetails`.
I've added `extendRoutes` function to the `nuxt.config.js` which supports /order-details/<id>. This change required refactoring `MyAccount` page.
I've added order-details middleware to disallow user from opening `/my-account/order-details` or `/my-account/order-details/<INCORRECT_ORDER_ID>` - in this case, user is being redirected to the `/my-account/order-history`
#187 
Previously, the navigation was unintuitive. The reactive state wouldn't support proper behaviors for navigating back while browsing orders history and …
=>  feat(#187): create order details page with nested dynamic paths

.dockerignore, Dockerfile, docker-entrypoint.sh
added dockerfile that can run a vsf app in production mode
Added dockerfile with customisable backend url under URL variable. The app is being run in production.
User can build docker image with command line:  docker build . -t vsf-main:new
Then run it by using command line: docker run -d -p 8000:3000 -e URL=https://demo.spreecommerce.org vsf-main:new
#174
It resolves #174
=> feat(#174): added dockerfile

packages/api-client/src/api/getMenus/index.ts, packages/api-client/src/api/serializers/menu.ts, packages/api-client/src/index.server.ts, packages/api-client/src/types/index.ts, packages/api-client/src/types/menu.ts, packages/composables/src/index.ts, packages/composables/src/types/index.ts, packages/composables/src/useMenus/index.ts, packages/theme/components/AppFooter.vue, packages/theme/components/HeaderNavigation.vue, packages/theme/middleware.config.js, packages/theme/pages/Category.vue
added API to pull menus and refactored navigation to use pulled links
implemented API to pull menus from backend, added deserialisers to convert given data to proper format and changed navigation through categories to use Menu if possible, if not the menu is still being build based on item slugs
#210
it solves #210
manually
=> feat(#210): add menu API and pull menu navigation using it

packages/api-client/src/api/serializers/product.ts
`(product.relationships.primary_variant?.data as RelationType).id || null;` still throws an error when `product.relationships.primary_variant` is null because we end up with `null.id || null`.
https://github.com/vuestorefront/spree/issues/223
=> fix: handling missing primary variant

packages/theme/pages/Category.vue
Added a fallback to slug when menu is not provided by api 
#236
It fixes #236
=> fix(#236): fix api navigation

packages/theme/components/AppHeader.vue
With this commit, the search overlay's visibility is handled properly.
The issue was found with incorrectly applied z-index, positioning, and hierarchy of elements.
https://user-images.githubusercontent.com/18665370/162462311-b59a3752-33e2-4a09-8ce8-1966dac04eb8.mov
#204
=> fix(#204): handle search overlay visibility properly 

packages/theme/nuxt.config.js, packages/theme/routes.ts
=> feat: add fixed paths as the single source of truth

.gitignore
This PR adds `.env`, `.env.development` and `.env.production` files to the `.gitignore` file.
=> feat: add env files to .gitignore

packages/theme/pages/Checkout/Billing.vue, packages/theme/pages/Checkout/Shipping.vue
I've reordered state inputs in both Shipping and Billing, to make them more accessible while using the keyboard.
#196
=> feat(#196): change position of state input in checkout pages

README.md, package.json, packages/theme/middleware.config.js, yarn.lock
This PR adds `.env` files support.
=> feat: add .env support

packages/api-client/package.json, yarn.lock
This PR updates the SDK version to 5.1.8
=> feat: update SDK version to 5.1.8

packages/theme/components/CartSidebar.vue
The product's sku can be an empty string which was causing a vue render warning since :key can't be an empty string. It has been changed to use variantId instead.
=> feat: update cart render loop

packages/theme/middleware/my-profile.js, packages/theme/middleware/order-details.js, packages/theme/nuxt.config.js, packages/theme/pages/MyAccount.vue, packages/theme/pages/MyAccount/OrderDetails.vue, packages/theme/routes.ts
This PR replaces the current page routing solution on my-account with `<nuxt-child />` component.
The usage of middlewares is also simplified because they now run only on a specific route they belong to (i.e. `order-details` middleware).
The current way of resolving sub-routes was not optimal - could have been coded better.
visually
=> feat: update my-account page to use nuxt child

packages/theme/pages/Home.vue, packages/theme/pages/MyAccount/OrderHistory.vue
This PR links `Shop now` buttons to the products categories page.
=> fix: link CTA buttons

packages/theme/middleware.config.js
=> feat: add spree 4.5 preset

packages/theme/assets/styles.scss, packages/theme/components/AppHeader.vue, packages/theme/components/RelatedProducts.vue, packages/theme/components/SearchResults.vue, packages/theme/package.json, packages/theme/pages/Category.vue, packages/theme/pages/Checkout/Payment.vue, packages/theme/pages/Product.vue, yarn.lock
This PR updates the Storefront UI to 0.12.3 according to the [migration guide](https://docs.storefrontui.io/v1/?path=/docs/releases-v0-12-x-v0-12-0-migration-guide--page).
The major refactoring relates to how SfImage component is defined. Now it requires width and height properties to determine the aspect ratio of an image. Then the size can be changed via css to fit the responsive layout.
More details: [here](https://github.com/vuestorefront/storefront-ui/pull/607).
=> chore: update Storefront UI to 0.12.3

packages/api-client/package.json, yarn.lock
=> chore: bump storefront SDK version to 6.0.6

packages/theme/pages/Home.vue
=> fix: add image width and height props to the product card

packages/api-client/src/api/getPaymentMethods/index.ts, packages/api-client/src/api/serializers/payment.ts, packages/api-client/src/types/checkout.ts
=> refactor: replace axios call with sdk method in getPaymentMethods

packages/theme/middleware.config.js
This PR adds a preset for Spree 4.6 and sets it as default.
=> feat: add Spree 4.6 preset
