- .eslintrc.json
- packages/api-client/src/api/addToCart/index.ts
- packages/api-client/src/api/authentication/getCurrentBearerToken.ts
- packages/api-client/src/api/changePassword/index.ts
- packages/api-client/src/api/getCategory/index.ts
- packages/api-client/src/api/getOrders/index.ts
- packages/api-client/src/api/getProducts/index.ts
- packages/api-client/src/api/saveCheckoutBillingAddress/index.ts
- packages/api-client/src/api/saveCheckoutShippingAddress/index.ts
- packages/api-client/src/api/saveShippingMethod/index.ts
- packages/api-client/src/api/serializers/address.ts
- packages/api-client/src/api/serializers/cart.ts
- packages/api-client/src/api/serializers/country.ts
- packages/api-client/src/api/updateItemQuantity/index.ts
While using camel case is common practice in JavaScript, some libraries or data may not follow this rule. Easing the `camelcase` ESLint rule removes errors associated with providing non camel case properties. For example, changing the `camelcase` setting will allow the following argument structure provided to a function:
```js
{
primary_variant: {...}
}
```
By changing the rule in `.eslintrc` we would avoid adding `/* eslint-disable camelcase */` in modules.
> Ignore non camel case property names

- README.md
- package.json
- packages/api-client/src/api/getProduct/index.ts
- packages/api-client/src/api/getProducts/index.ts
- packages/api-client/src/api/serializers/common.ts
- packages/api-client/src/api/serializers/product.ts
- packages/api-client/src/index.server.ts
- packages/api-client/src/types/index.ts
- packages/api-client/tsconfig.json
- packages/theme/middleware.config.js
- yarn.lock
A product may have no images, images associated with the primary variant, images associated with the default or miscellaneous variants. This PR handles most possible combinations. It doesn't search for images in variants other than current, primary or default. Still, it's an improvement over the current approach and finds more images.
> Attempt to use primary, default and viewed variants' images

- packages/api-client/src/api/getCart/index.ts
- packages/api-client/src/api/serializers/cart.ts
- packages/api-client/src/types/cart.ts
- packages/composables/src/getters/cartGetters.ts
As discussed, we should use item count from Spree, to make the displayed count consistent with Spree's built-in frontend
> Update cart item count

- packages/api-client/src/api/internationalization/integration.ts
- packages/api-client/src/types/index.ts
there was no function to get current locale of vue storefront
i create some addition to have the ability to get current locale and use inside api-client package
now you can get current locale of your storefront
manualy with console.log
> add getLocale to api-client package

- packages/api-client/src/api/getProducts/index.ts
Reducing the array of filter objects, by assigning each filter value to its relative key caused overriding the key's value and calling the API with only the most recently applied one.
With this commit, values are stringified, separated by a comma, and assigned to their relative key. In the properties object.
Having 
```
optionTypeFilters = [
{productPropertyName: 'brand', productPropertyValue: 'alpha'},
{productPropertyName: 'brand', productPropertyValue: 'beta'}
]
```
Before:
```properties = {brand: 'beta'}```
Now:
```properties =  {brand: 'alpha,beta'}```
The same applies to manufacturers.
#109
It solves #109  - Selecting multiple filters for Brand and Manufacturer caused applying only the most recently selected one.
Manually, by debugging state of properties and verifying response send …
> fix(#109): pass Brand/Manufacturer filter properties correctly

- packages/composables/src/getters/orderGetters.ts
With this commit, the counter of total user orders displays a proper value based on an actual length of orders.
Updated hard-coded value with an actual length of user orders, which defaults to `0` if the given `orders` object is null.
Fixes #124.
Manually, by verifying backend response and frontend layer.
> fix(#124): display total orders value based on user orders

- packages/theme/components/Checkout/VsfShippingProvider.vue
Knowing it's not valid to have an empty list of shipping methods, we can establish whether values are loaded or not by checking the length of the values array. There are only 2 categories for length of the `allShipmentsSelected`: empty - not loaded, not empty - loaded. Hence, there's no need for checking if the promise has been resolved. Null checks are redundant since the initial state of the `selectedShippingRates` field is an empty object, which then is only modified by `reduce` method or the spread operator, in the current configuration they both don't return null values.
Solves #116
Manually, by debugging states of selectedShippingRates and allShipmentsSelected to establish the correctness of the solution.
https://user-images.githubusercontent.com/18665370/157465575-3fec9713-ca8f-42f4 …
> fix(#116): disable the 'continue' button when shipping is loading

- packages/theme/pages/Product.vue
With this commit, switching between tabs in the Product Info panel no longer leads to layout shifts.
Setting a fixed width of 100% to the Product info container always maintains the maximal possible width. Having a maximal possible width of the container won't lead to layout shifts if the content inside gets shorter.
#136
Layout shifts lead to poor UX quality.
https://user-images.githubusercontent.com/18665370/158425443-17cac647-e9a8-4815-b98d-f45287abe4d9.mov
> fix(#136): avoid layout shifts of the product info panel

- packages/theme/pages/MyAccount/OrderHistory.vue
With this commit, visiting the order history page while having no orders on the account, no longer results in seeing the error page.
The issue was found in the core library of the Vue Storefront; hence, creating our own version of the OrderHistory page was required in order to modify the computed value of orders. In the core library, orders were computed by retrieving the `results` field on the `orders.value` object. The problem was caused by the fact, `orders.value` is an array of orders, so it couldn't return the `results` field.
#118
It solves #118.
Manually, by testing different scenarios (user with no orders, user with 1 and more orders)\
> fix(#118): display order history accordingly to the backend response

- packages/theme/pages/Checkout/Shipping.vue
Add an option to use the same address for billing instead of tying it twice
added checkbox that allows user to pass the provided shipment data to billing address so the person using site will not have to type the same details twice
#132
manually
> feat: add an option to use the same address for billing

- packages/theme/pages/MyAccount/OrderHistory.vue
The returns tab needed to be deleted because it is not planned to be implemented (at least soon).
#141
> feat: delete the returns tab from order history in my account section

- packages/api-client/src/api/serializers/cart.ts
Every order in the orders history was showing the same products. That was a problem related to deserialisation.
Closes #183 
It was tested in the local environment connected to our test backend.
> fix: orders history fixed

- packages/api-client/src/api/serializers/cart.ts
`formatImageUrl` function needs `config` object as a param (in order to have an access to `backendUrl` and `assetsUrl`), but in the `deserializeLineItem` function, we are passing `backendUrl` string instead. That's why when line item has an image, `formatImageUrl` function throws an error (can't read `.concat` of `undefined`)
> fix: update deserializing line item image

- packages/theme/components/AppHeader.vue
- packages/theme/components/HeaderNavigation.vue
Fixed disappearing menu and refactored it to be show all categories
On mobile version:
After a few click on the menu observers were closed one by one and it did not show up anymore. Added a function that changes the amount of observers to nullify disappearing ones. Also refactored a bit menu shows in products tab so it shows all the possible categories 
#121
Menu does not work properly without those changes and it could be confusing to the user.
manually by checking observers
> fix: fixed missing menu and refactored it to show all categories

- packages/api-client/src/api/serializers/cart.ts
- packages/api-client/src/types/cart.ts
- packages/composables/src/getters/cartGetters.ts
- packages/composables/src/getters/orderGetters.ts
- packages/theme/components/CartSidebar.vue
- packages/theme/pages/MyAccount/OrderHistory.vue
Products in the Order History didn't redirect to their pages, instead they did redirect to blank "not found" pages. These changes introduce proper id and slug passing, so there can be proper links created. Also did the same thing for products in the cart. 
Closes #185 
Changes for the cart and order history give more natural and intuitive feeling while using the app.
It was tested in the local environment connected to our Heroku backend.
> fix(#185): checkout and order products now link to themselves

- packages/theme/components/CartSidebar.vue
Products' option values were displayed even if there was blank space, now they're shown only if they exist.
Closes #201 
Local environment with Spree 4.4 backend on Heroku.
Before
After
> feat(#201): products in the cart now display option values only if they exist

- packages/theme/pages/Product.vue
There was an issue where backend returned products' descriptions including the html tags, which were shown instead of compiled. These changes fix it.
Local environment with our backend.
> fix: rendering products' descriptions fixed

- packages/theme/components/Checkout/AddressPicker.vue
- packages/theme/components/Checkout/VsfShippingProvider.vue
- packages/theme/pages/Checkout/Shipping.vue
Disabled an option to change shipping details when user already called for shipping methods
Removed possibility to change shipping details after user calls for shipping methods so it won't throw an error in special cases. Added a button that takes user back so she/he can provide details once more and choose appropriate shipping method. Also now while choosing shipping method user can go back to shipping details just by clicking on any of the input  fields or just by clicking saved address(only for logged in users)
#165
It fixes #165
manually
> fix(#165): removed an option to change shipping details after shipment 

- packages/theme/components/AppHeader.vue
- packages/theme/pages/MyAccount.vue
With this commit, the isMobile property (with its own getter method) of the mobile-observer utility is exposed inside of the computed value, and not using ref() or computed(() => ...), which may lead to unwanted results.
> fix(theme): update mobile-observer usage with computed property accessed via its getter

- packages/theme/assets/components/_SfProductCard.scss
- packages/theme/assets/styles.scss
- packages/theme/nuxt.config.js
With this commit, alternative text on image cards is visible and overflows with an ellipsis. Additionally, image containers inside of image cards fill the empty space, to match other containers' heights in the row and no longer shrink if the image is not available.
I've also added support for the global SCSS styles and created an assets/components directory for partials overriding components' styles globally which are linked using `styleResources` in the nuxt.config file.
14.png)
> feat(theme): add support for visible alternative text in cover images

- packages/api-client/src/api/serializers/product.ts
The type signature was invalid - nullish coalescing returns `undefined`.
> fix: nullish coalescing type signature return value

- packages/composables/src/types/index.ts
Errors while compiling:
```
[dev:theme]  WARN  Compiled with 7 warnings
[dev:theme]
[dev:theme]
[dev:theme]  WARN  in ../composables/lib/index.es.js
[dev:theme]
[dev:theme]
[dev:theme]  WARN  in ../composables/lib/index.es.js
[dev:theme]
[dev:theme] "export 'Cart' was not found in '@vue-storefront/spree-api'
[dev:theme]
[dev:theme] "export 'Category' was not found in '@vue-storefront/spree-api'
[dev:theme]
[dev:theme] "export 'LineItem' was not found in '@vue-storefront/spree-api'
[dev:theme]
[dev:theme]
[dev:theme]  WARN  in ../composables/lib/index.es.js
[dev:theme]
[dev:theme]
[dev:theme]  WARN  in ../composables/lib/index.es.js
[dev:theme]
[dev:theme]
[dev:theme]  WARN  in ../composables/lib/index.es.js
[dev:theme]
[dev:theme] "export 'Order' was not found in …
```
> chore: use type-only exports to avoid import warnings

- packages/theme/pages/Category.vue
```
TypeError
Cannot read property '$i18n' of undefined
```
We are using the regular composition API context in some places (second argument of `setup()`) and the Nuxt one in other (`useContext()`). The Nuxt context does not contain `root`, the plugins are stored under `app`.
Changing the context in `Category.vue` to be the Vue one (second argument) causes Nuxt SSR errors so I stuck with `useContext` in this file.
> fix: use Nuxt context properties in `Category.vue` page

- packages/theme/components/AppFooter.vue
When adding dynamic menus to AppFooter recently, we missed a case when the footer isn't loaded instantly or is not configured in the backend. This shouldn't block the frontend from working.
Fix issue with rendering pages.
Manual tests
> fix: handle app footer when there is no menu configured

- README.md
I don't think it's optional. E.g. `api-client` has to be built before `composables` and `theme` and `yarn dev` does not guarantee that because it runs the tasks concurrently. This leads to errors such as these:
```
[dev:composables] [!] (plugin rpt2) Error: /Users/karolszuster/Upside/vsf/tmp/spree/packages/composables/src/useBilling/index.ts(2,25): semantic error TS2307: Cannot find module '@vue-storefront/spree-api' or its corresponding type declarations.
[dev:composables] src/useBilling/index.ts
[dev:composables] Error: /Users/karolszuster/Upside/vsf/tmp/spree/packages/composables/src/useBilling/index.ts(2,25): semantic error TS2307: Cannot find module '@vue-storefront/spree-api' or its corresponding type declarations.
[dev:composables]     at error …
```
> chore: do not mark the `yarn build` step as optional in readme

- packages/api-client/src/api/serializers/product.ts
Related issue: https://github.com/vuestorefront/spree/issues/112
> fix: handle products with no taxons when building breadcrumbs

- packages/theme/components/AppHeader.vue
- packages/theme/components/HeaderNavigation.vue
- packages/theme/components/LocaleSelector.vue
Updates to HeaderNavigation and LocaleSelector to resolve hydration errors when loading on mobile. This involves removing the use of v-if directives using 'isMobile' and instead using "desktop-only" and "smartphone-only" classes, as isMobile is undefined on the server-side. Also added a root div.
Per issue #241 
Hydration error as noted in issue.
Tested locally on Chrome. Updates resolve the hydration error.
N/A
> fix: resolve hydration error on HeaderNavigation and LocaleSelector

- README.md
Update broken link in Readme to Vue Storefront documentation.
#240 
Keep documentation up to date.
> fix: update broken link to vue storefront documentation

- packages/theme/nuxt.config.js
- packages/theme/pages/Category.vue
As noted in issue, products IDs currently in the URL are redundant. 
This PR updates the routing to remove them from the product URLs.
My preference would be for the default to be `/products/:slug` (rather than `/p/:slug`), as this has been the default for Spree stores in the past (and keeping this will be better for SEO, and reduce the need for redirects). Thoughts?
#221 
To simplify URL and remove extra integration steps.
Tested locally on Chrome 103.0.5060.114
> feat: remove product id from url

- packages/theme/components/Checkout/VsfShippingProvider.vue
- packages/theme/pages/Checkout/Shipping.vue
When the user selects the "use the same details for billing" and selects their shipping method on the shipping page, the user should be able to skip the "billing address" page and go directly to the payment page (as the billing address has already been saved).
#245 
Improved user experience. Less checkout steps = Higher conversion rate.
Tested locally on chrome.
> feat: add ability to skip billing step

- packages/theme/components/LoginModal.vue
- packages/theme/components/MyAccount/PasswordResetForm.vue
- packages/theme/components/MyAccount/SavedAddressForm.vue
- packages/theme/lang/de.js
- packages/theme/lang/en.js
- packages/theme/pages/Checkout/Billing.vue
- packages/theme/pages/Checkout/Shipping.vue
- packages/theme/pages/ResetPassword.vue
With this commit, vee-validate extended error messages are now localized.
Moved all extend(...) vee-validate function calls into created() method and used i18n to localize messages.
Messages are localized for global scope, not component/page specific. This is done, to achieve consistency across different forms.
https://github.com/vuestorefront/spree/pull/249
Providing full internationalization support.
> feat: localize validation errors

- packages/theme/components/Checkout/ShippingRatePicker.vue
- packages/theme/components/Checkout/VsfShippingProvider.vue
With this commit, all shippings are preselected with data returned from the API.
I've removed code responsible for constructing `selectedShippingRates` object and created a `mounted` lifecycle option in the `ShippingRatePicker` which indirectly calls `selectShippingRate` with shipmentId and shippingRateId instead. Added defensive check to make sure all required shippings are added to the `selectedShippingRates` by the `ShippingRatePicker`-s calls.
#179 
Poor UX. Users had the shipping method selected, but returning to the shipping view and opening the shipping method step again wouldn't show that to them in the UI.
https://user-images.githubusercontent.com/18665370/160780710-783f32f2-7259-4934-a7c3-8337fa002e40.mov
> feat(#179): add preselection to shipping methods

- packages/theme/pages/Checkout/Billing.vue
- packages/theme/pages/Checkout/Shipping.vue
With this PR, when a user logs in during the checkout process, the saved addresses will be loaded.
I've added a watcher for `isAuthenticated` value, which loads necessary data if a user gets authenticated on the shipping/billing page. The watcher updates already filled form values with checkoutShippingAddress/checkoutBillingAddress, so that the user won't lose provided data (Imagine a case, where a user filled some of the form fields and decided to log in afterward; we don't want to lose that data).
I've also removed reused code in lifecycle methods for form.value.country and transformed already existing watcher into the [eager watcher](https://vuejs.org/guide/essentials/watchers.html#eager-watchers) where I've implemented removed code.
#158 
A user couldn't get their saved addresses …
> fix(#158): load saved addresses on successful authentication during checkout

- packages/api-client/src/index.server.ts
This PR reverts to the old way of importing api fetchers from the dist folder due to the SDK revert PR ([#348](https://github.com/spree/spree-storefront-api-v2-js-sdk/pull/348)).
> feat: revert the api fetcher import

- packages/api-client/src/api/getCMSPages/index.ts
- packages/api-client/src/api/serializers/page.ts
- packages/api-client/src/index.server.ts
- packages/api-client/src/types/page.ts
- packages/composables/src/types/content.ts
- packages/composables/src/useContent/index.ts
- packages/theme/nuxt.config.js
- packages/theme/pages/Home.vue
This PR adds basic support for spree homepage configuration.
I have also added a `getCMSPages` api endpoint which returns a list of pages matching the applied filter.
> feat: add homepage cms support

- app.json
- docs/.vuepress/config.js
- docs/guide/configuration.md
- docs/guide/feature-support.md
- docs/guide/getting-started.md
- docs/index.md
This PR updates the docs to properly reflect the configuration and set up process with the most recent 4.5 spree version.
> feat: update docs

- packages/api-client/package.json
- packages/api-client/src/api/getCategory/index.ts
- packages/api-client/src/api/getProduct/index.ts
- yarn.lock
This PR adds current locale to Spree api calls params for getting the products and taxons. The locale is being taken from the cookie set by i18n nuxt plugin.
Spree SDK PR: https://github.com/spree/spree-api-v2-js-sdk/pull/364
> feat: add localization for products and taxons

- packages/theme/components/HeaderNavigation/DesktopMenu.vue
- packages/theme/components/HeaderNavigation/MobileMenu.vue
This PR adds additional checks for the menu prop which is falsy when the menu is not configured in Spree backend. With the checks in place, only a "please configure..." info will show up on the frontend.
> fix: add menu prop checks in the menu components

- packages/theme/nuxt.config.js
- packages/theme/package.json
- yarn.lock
Previously the middlewareUrl parameter was composed using `new URL`. However, this approach removes the base url subpath making the final url invalid. For example `new URL('/api', 'http://localhost:3000/shop/').href` will result in `http://localhost:3000/api` instead of desired `http://localhost:3000/shop/api`.
This caused middleware connection errors when trying to serve the app under a subpath.
> fix: use path join to compose the middleware url

- packages/api-client/src/api/getCategory/index.ts
- packages/api-client/src/api/getProduct/index.ts
- packages/api-client/src/api/getProducts/index.ts
- packages/api-client/src/api/serializers/category.ts
- packages/api-client/src/api/serializers/product.ts
- packages/api-client/src/types/category.ts
- packages/api-client/src/types/product.ts
- packages/composables/src/getters/categoryGetters.ts
- packages/theme/helpers/localizedSlugsToRouteParams.ts
- packages/theme/pages/Category.vue
- packages/theme/pages/Product.vue
This PR adds the `localized_slugs` property to product and taxon serializers making it accessible on the frontend. Then it is being parsed by the `localizedSlugsToRouteParams` function and passed to the `i18n/setRouteParams` dispatch to set the alternative routes ([docs](https://i18n-legacy.nuxtjs.org/lang-switcher#dynamic-route-parameters)).
When switching between languages on product and category page the user should be redirected to the translated url defined in Spree backend.
visually
> feat: add language switcher based on localized slugs coming from Spree

- packages/api-client/src/api/serializers/product.ts
This PR removes the addHostToImage function from the api serializers and all of the places it has been referenced.
Before a product image url coming from Spree didn't include the host. Right now it returns a full url so it's not needed to prefix the host.
Images weren't showing because the final url was invalid.
> fix: prepend hostname to image urls only when it's not preset

- README.md
- packages/theme/nuxt.config.ts
This PR adds a `base` property to the router config based on the `BASE_URL` env variable making it easy to configure the store to be served under a subpath.
https://github.com/vuestorefront-community/spree/issues/294
> feat: base url subpath

- .github/workflows/docs-deployment.yml
elgohr/Publish-Docker-Github-Action@master is not supported anymore
> Updated elgohr/Publish-Docker-Github-Action to a supported version (v5)
